import { useMemo,useState } from 'react'
import { ArrowDownRight,ArrowRight,ArrowUpRight,Bell,Box,CalendarDays,ChevronDown,CircleDollarSign,Download,LayoutDashboard,Menu,MoreHorizontal,Package,Search,Settings,ShoppingCart,TrendingUp,Users,WalletCards,X } from 'lucide-react'
const orders=[
 {id:'#1048',customer:'Marina Alves',email:'marina@email.com',avatar:'https://i.pravatar.cc/70?img=47',product:'Poltrona Serena',value:1290,status:'Pago',date:'Hoje, 14:32'},
 {id:'#1047',customer:'Caio Mendes',email:'caio@email.com',avatar:'https://i.pravatar.cc/70?img=11',product:'Luminária Alba',value:389,status:'Processando',date:'Hoje, 13:18'},
 {id:'#1046',customer:'Isabela Rocha',email:'isa@email.com',avatar:'https://i.pravatar.cc/70?img=32',product:'Mesa Lateral Noma',value:579,status:'Pago',date:'Hoje, 11:45'},
 {id:'#1045',customer:'Pedro Lima',email:'pedro@email.com',avatar:'https://i.pravatar.cc/70?img=13',product:'Conjunto Senda',value:319,status:'Reembolsado',date:'Ontem, 18:20'},
 {id:'#1044',customer:'Ana Clara',email:'ana@email.com',avatar:'https://i.pravatar.cc/70?img=44',product:'Manta Bruma',value:229,status:'Pago',date:'Ontem, 16:02'},
]
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value)
const periods:{[key:string]:number}={'7 dias':.32,'30 dias':1,'90 dias':2.74,'12 meses':10.8}
function App(){
 const [period,setPeriod]=useState('30 dias'),[menu,setMenu]=useState(false),[search,setSearch]=useState(''),[notice,setNotice]=useState(false)
 const factor=periods[period],filtered=useMemo(()=>orders.filter(order=>`${order.id} ${order.customer} ${order.product}`.toLowerCase().includes(search.toLowerCase())),[search])
 const nav=[['Visão geral',LayoutDashboard],['Pedidos',ShoppingCart],['Produtos',Package],['Clientes',Users],['Financeiro',WalletCards]] as const
 return <main className="app">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span>n</span>norte</div><button className="close-menu" onClick={()=>setMenu(false)}><X/></button><p>GESTÃO</p><nav>{nav.map(([label,Icon],index)=><a className={index===0?'active':''} href={`#${label}`} key={label}><Icon/>{label}{label==='Pedidos'&&<i>12</i>}</a>)}</nav><p>SISTEMA</p><nav><a href="#config"><Settings/>Configurações</a></nav><div className="upgrade"><div><TrendingUp/></div><strong>Potencialize seus dados</strong><span>Desbloqueie relatórios avançados no plano Pro.</span><button>Conhecer o Pro</button></div><div className="profile"><img src="https://github.com/RBC-ImktNet.png"/><div><strong>Ricardo Cardoso</strong><span>Administrador</span></div><MoreHorizontal/></div></aside><div className={menu?'menu-overlay open':'menu-overlay'} onClick={()=>setMenu(false)}/>
  <section className="content"><header><button className="open-menu" onClick={()=>setMenu(true)}><Menu/></button><label className="global-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar pedidos, clientes..."/><kbd>⌘ K</kbd></label><div className="header-actions"><button className="notification" onClick={()=>setNotice(!notice)}><Bell/><i/></button><button className="help">?</button><div className="user"><img src="https://github.com/RBC-ImktNet.png"/><span>Ricardo</span><ChevronDown/></div></div>{notice&&<div className="notification-pop"><strong>Notificações</strong><p>3 novos pedidos foram confirmados.</p><p>O relatório mensal está disponível.</p></div>}</header>
   <div className="dashboard"><div className="page-head"><div><span>PAINEL DE CONTROLE</span><h1>Visão geral</h1><p>Acompanhe o desempenho da sua operação.</p></div><div><label><CalendarDays/><select value={period} onChange={e=>setPeriod(e.target.value)}>{Object.keys(periods).map(item=><option value={item} key={item}>Últimos {item}</option>)}</select><ChevronDown/></label><button><Download/>Exportar</button></div></div>
   <div className="metrics">{[
    {label:'Receita total',value:money(128450*factor),change:'+12,8%',up:true,icon:CircleDollarSign,color:'violet'},
    {label:'Pedidos',value:Math.round(1248*factor).toLocaleString('pt-BR'),change:'+8,4%',up:true,icon:ShoppingCart,color:'blue'},
    {label:'Ticket médio',value:money(417),change:'+3,2%',up:true,icon:WalletCards,color:'green'},
    {label:'Reembolsos',value:money(2840*factor),change:'−1,6%',up:false,icon:ArrowDownRight,color:'orange'}
   ].map(({label,value,change,up,icon:Icon,color})=><article key={label}><div className={`metric-icon ${color}`}><Icon/></div><div className="metric-top"><span>{label}</span><MoreHorizontal/></div><strong>{value}</strong><p className={up?'positive':'negative'}>{up?<ArrowUpRight/>:<ArrowDownRight/>}{change}<i>vs. período anterior</i></p></article>)}</div>
   <div className="charts"><article className="revenue-card"><div className="card-head"><div><span>DESEMPENHO</span><h2>Receita</h2></div><div className="legend"><i/><span>Este período</span><i/><span>Anterior</span></div><button><MoreHorizontal/></button></div><div className="chart"><div className="y-axis"><span>R$ 50k</span><span>R$ 40k</span><span>R$ 30k</span><span>R$ 20k</span><span>R$ 10k</span><span>R$ 0</span></div><div className="plot"><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7467e8" stopOpacity=".25"/><stop offset="1" stopColor="#7467e8" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 198 C60 180,70 175,115 167 S180 172,230 135 S310 150,350 112 S440 110,470 76 S550 102,590 54 S660 55,700 28 L700 230 L0 230Z"/><path className="current-line" d="M0 198 C60 180,70 175,115 167 S180 172,230 135 S310 150,350 112 S440 110,470 76 S550 102,590 54 S660 55,700 28"/><path className="previous-line" d="M0 210 C60 200,80 183,120 189 S190 181,235 165 S310 171,355 145 S430 154,475 119 S550 128,595 95 S665 105,700 79"/></svg><div className="x-axis"><span>01 jun</span><span>06 jun</span><span>12 jun</span><span>18 jun</span><span>24 jun</span><span>30 jun</span></div></div></div></article>
    <article className="channels"><div className="card-head"><div><span>AQUISIÇÃO</span><h2>Vendas por canal</h2></div><button><MoreHorizontal/></button></div><div className="donut"><div><strong>1.248</strong><span>pedidos</span></div></div><div className="channel-list">{[['Loja online','58%','violet'],['Marketplace','24%','blue'],['Redes sociais','12%','green'],['Outros','6%','gray']].map(([name,value,color])=><div key={name}><i className={color}/><span>{name}</span><strong>{value}</strong></div>)}</div></article></div>
   <div className="bottom-grid"><article className="orders"><div className="card-head"><div><span>ATIVIDADE RECENTE</span><h2>Últimos pedidos</h2></div><a href="#pedidos">Ver todos<ArrowRight/></a></div><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Produto</th><th>Valor</th><th>Status</th><th>Data</th><th/></tr></thead><tbody>{filtered.map(order=><tr key={order.id}><td><strong>{order.id}</strong></td><td><div className="customer"><img src={order.avatar}/><div><strong>{order.customer}</strong><span>{order.email}</span></div></div></td><td>{order.product}</td><td><strong>{money(order.value)}</strong></td><td><span className={`status ${order.status.toLowerCase()}`}>{order.status}</span></td><td>{order.date}</td><td><MoreHorizontal/></td></tr>)}</tbody></table></div></article>
   <article className="activity"><div className="card-head"><div><span>EM TEMPO REAL</span><h2>Atividade</h2></div><i className="live"/></div>{[['payment','Pagamento confirmado','Pedido #1048 • R$ 1.290','Agora'],['order','Novo pedido recebido','Pedido #1047 • R$ 389','12 min'],['stock','Estoque atualizado','Luminária Alba • 24 un.','38 min'],['customer','Novo cliente cadastrado','Ana Clara','1h']].map(([type,title,desc,time])=><div className="activity-item" key={title}><div className={`activity-icon ${type}`}><Box/></div><div><strong>{title}</strong><span>{desc}</span></div><time>{time}</time></div>)}</article></div>
   </div>
  </section>
 </main>
}
export default App
